nelmio_api_doc:
    documentation:
        info:
            title: Articles and Tags
            description: This is the API documentation for the project
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)

